"""Message published after the AI service finishes processing a transcript."""

from datetime import datetime, timezone

from src.models.msg.abstract_message import AbstractMessage


class AICompletedMessage(AbstractMessage):
    """Message published when AI processing of a transcript is complete.

    Attributes:
        filename: Original name of the audio file that was transcribed.
        summary: Clinical summary generated by the AI.
        prescription: Extracted prescription data as a JSON-serialisable dict.
        processed_at: UTC timestamp of when AI processing completed.

    """

    filename: str
    summary: str
    prescription: dict[str, object]
    processed_at: datetime = None  # type: ignore[assignment]

    def model_post_init(self, __context: object) -> None:
        """Set processed_at to current UTC time if not provided."""
        if self.processed_at is None:
            object.__setattr__(self, "processed_at", datetime.now(tz=timezone.utc))
