"""update appointment uuid and statuses

Revision ID: 360e5e1dcef8
Revises: df409e9d2aa9
Create Date: 2026-03-10 13:06:09.113585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360e5e1dcef8'
down_revision: Union[str, Sequence[str], None] = 'df409e9d2aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
