"""Message received from the ai.completed exchange."""

import uuid
from datetime import datetime

from src.models.msg.abstract_message import AbstractMessage


class AICompletedMessage(AbstractMessage):
    """Message published by ai-service when processing a transcript is complete.

    Attributes:
        filename: Original name of the audio file that was transcribed.
        summary: Clinical summary generated by the AI.
        prescription: Extracted prescription data as a JSON-serialisable dict.
        processed_at: UTC timestamp of when AI processing completed.
        consultation_id: ID of the consultation this result belongs to.

    """

    filename: str
    summary: str
    prescription: dict[str, object]
    processed_at: datetime
    consultation_id: uuid.UUID
